version: '3.8'
volumes:
  db-store:

networks:
  default:
    external:
      name: api_network

services:
  admin:
    build: .
    container_name: test_api_client
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - ..:/usr/src/admin/
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-go_local}
      - DB_USERNAME=${DB_USER:-user1}
      - DB_PASSWORD=${DB_PASS:-secret}
    ports:
      - 18081:8080
  